var strategies = {
    maa_archers: {
        dark_headers: ['Sheep', 'Wood', 'Boar', 'Berries', 'Boar/sheep', 'Build Barracks to Wood', 'Gold'],
        dark_values: [6, 4, 2, 4, '2 (10)', 1, 2],
        dark_instructions: '',
        fup_instructions: 'While advancing send 2 sheep to wood, 2 to berries, 2 to farms',
        feudal_headers: ['Wood', 'Gold', 'Farms', 'Wheelbarrow'],
        feudal_values: ['5 (12)', '6 (8)', '16 (18)', '+'],
        feudal_instructions: 'build 2 ranges then blacksmith',
    },
    scouts_archers: {
        dark_headers: ['Sheep', 'Wood', 'Boar', 'Berries', 'Boar to farms', 'Wood'],
        dark_values: [6, 3, 2, 4, 2, '4 (7)'],
        dark_instructions: '',
        fup_instructions: 'On advance move 3 sheep to wood (10); build barracks',
        feudal_headers: ['Farms', 'Gold', 'Wheelbarrow', 'Farms'],
        feudal_values: ['8 (14)', '6 (+2 from berries - 8)', '+', '2 (18)'],
        feudal_instructions: 'build stable, then 2 ranges and Blacksmith',
    },
    scouts_castle: {
        dark_headers: ['Sheep', 'Wood', 'Boar', 'Berries', 'Boar to farms', 'Wood'],
        dark_values: [6, 3, 2, 4, 2, '4 (7)'],
        dark_instructions: '',
        fup_instructions: 'On advance move 3 sheep to wood (10); build barracks',
        feudal_headers: ['Farms', 'Gold', 'Farms', 'Wheelbarrow'],
        feudal_values: ['8 (14)', '4 (6)', '1 (15)', '+'],
        feudal_instructions: 'build stable with 2 vills; after farms build Blacksmith, move 2 berries to gold',
        cup_instructions: 'While advancing, build second stable',
    },
};
var civs = {
    aztecs: { strategy: 'Meso eagles; imp add monks vs cavalry',
        dark_headers: ['Sheep', 'Wood', 'Boar', 'Berries', 'Boar to farms', 'Wood'],
        dark_values: [6, 4, 2, 4, 2, '3 (7)'],
        dark_instructions: '',
        fup_instructions: 'While advancing: 4 sheep to gold, build 2 barracks',
        feudal_headers: ['Wood', 'Gold', 'Farms'],
        feudal_values: ['3 (10)', '2 (4)', '+'],
        feudal_instructions: 'build blacksmith',
        cup_instructions: '',
        castle_headers: [],
        castle_values: [],
        castle_instructions: '',
        eco: '50+ Gold, Vills Carry +5',
        team: 'Relics +33% gold',
        military: 'Army created 15% faster, Monk + HP',
        uu: 'Jaguar Warrior (Infantry)',
        utech: 'Skirmisher +1 att & rng, Infantry +4 att',
        opening: 'Man-At-Arms',
        transition: 'Archers',
        castle: 'Monks + Relics + Eagles',
        imp: 'Eagles + Trash + Siege'
    },
    britons: { strategy: 'Meta',
        dark_headers: ['Sheep', 'Wood', 'Boar', 'Berries', 'Boar to farms', 'Wood'],
        dark_values: [5, 4, 2, 4, 1, '5 (9)'],
        dark_instructions: '',
        fup_instructions: 'While advancing: 2 sheep to wood (11), 3 to gold; build 1 barracks',
        feudal_headers: ['Gold', 'Farms', 'Wheelbarrow'],
        feudal_values: ['5 (8)', '10 (18)', '+'],
        feudal_instructions: 'build 2 ranges then blacksmith',
        cup_instructions: '',
        castle_headers: [],
        castle_values: [],
        castle_instructions: '',
        eco: 'TC cost half wood, eat sheep faster',
        team: 'Arch Ranges work faster',
        military: 'Archers +1 rng in Cst/Imp',
        uu: 'Longbowman (Archer)',
        utech: '+1/+2 rng arch/tower, Trebs blast damage',
        opening: 'Man-At-Arms',
        transition: 'Archers',
        castle: 'Archers + Halbs/Cav',
        imp: 'Archers + Trebs + Trash',
        ...strategies.maa_archers
    },
    celts: { strategy: 'Meta',
        dark_headers: ['Sheep', 'Wood', 'Boar', 'Berries', 'Gold to Wood', 'Barracks to Houses', 'Wood', 'Sheep to Farms'],
        dark_values: [6, 3, 1, 4, 1, 1, '3 (7)', '8 (8 farms)'],
        dark_instructions: '',
        fup_instructions: 'Sheep gone: 4 sheep to gold, 2 to berries',
        feudal_headers: ['Wood'],
        feudal_values: ['2 (9)'],
        feudal_instructions: 'build blacksmith and market',
        cup_instructions: '',
        castle_headers: [],
        castle_values: [],
        castle_instructions: '<h4>Castle Age</h4>4 Siege Workshops',
        eco: 'Lumber work faster, Sheep loyalty',
        team: 'Siege works faster',
        military: 'Infantry move faster, Siege fires faster',
        uu: 'Woad raider (Infantry)',
        utech: 'Castles+Towers fire faster, Siege Units +HP',
        opening: 'Man-At-Arms',
        transition: 'Archers/Skirms',
        castle: 'Halbs + Siege',
        imp: 'Halbs + Siege + Woads',
        ...strategies.maa_archers
    },
    chinese: { strategy: 'Scout to Skirms; Elite Chu Ko Nu post imp',
        dark_headers: ['Loom', 'Sheep', 'Wood', 'Boar', 'Berries', 'Boar to farms', 'Wood'],
        dark_values: ['+', 7, 3, 1, 4, 2, '4 (7)'],
        dark_instructions: '',
        fup_instructions: 'While advancing: 3 sheep to wood, build 1 barracks',
        feudal_headers: ['Farms', 'Wood', 'Gold', 'Wheelbarrow', 'Farms'],
        feudal_values: ['8 (14)', '2 (12)', 2, '+', '4 (18)'],
        feudal_instructions: 'build stable with 2 vills, Range and Blacksmith after 6 scouts, move 2 berries to gold',
        cup_instructions: '',
        castle_headers: [],
        castle_values: [],
        castle_instructions: '',
        eco: '+3 vills, cheap tech, TC +5 LOS +10 Pop',
        team: 'Farms +45 food',
        military: 'Demo ships HP',
        uu: 'Chu Ko Nu (Archer)',
        utech: 'Walls & Towers +HP, Chu Ko Nu+2 & Scorp +4 att',
        opening: 'Scouts',
        transition: 'Archers/Skirms',
        castle: 'Archers + Cav',
        imp: 'Chu Ko Nu + Trash + Rams/Trebs'
    },
    franks: { strategy: 'Meta',
        dark_headers: ['Sheep', 'Wood', 'Boar', 'Berries', 'Boar to farms', 'Wood', 'Gold'],
        dark_values: [6, 4, 2, 4, 2, '6 (10)', 3],
        dark_instructions: '',
        fup_instructions: 'Sheep done: 6 (8) to farms, 2 (6) to berries, build 1 barracks',
        feudal_headers: ['Gold'],
        feudal_values: ['2 (5)'],
        feudal_instructions: 'build stable, blacksmith',
        cup_instructions: 'While advancing: 1 berries to gold (6), 2 berries to farms (10), build stable',
        castle_headers: [],
        castle_values: [],
        castle_instructions: '',
        eco: 'Berries gather faster, free farm upgrade',
        team: 'Knights +2 LOS',
        military: 'Cheap Castles, Cavaltry +HP',
        uu: 'Throwing Axeman (Infantry)',
        utech: 'Stables work faster, +1 Axeman range',
        opening: 'Scouts',
        transition: 'Fast Castle',
        castle: 'Knights + Halb/Skirm (get relics)',
        imp: 'Cav + Axemen + Trebs',
        ...strategies.scouts_castle
    },
    huns: { strategy: 'Meta',
        dark_headers: ['Sheep', 'Wood', 'Boar', 'Berries', 'Gold to Wood', 'Barracks to Houses', 'Wood', 'Sheep to Farms'],
        dark_values: [6, 4, 1, 4, 1, 1, '3 (8)', '8 (8 farms)'],
        dark_instructions: '',
        fup_instructions: 'Sheep gone: 4 sheep to gold, 2 to berries',
        feudal_headers: ['Wood'],
        feudal_values: ['2 (10)'],
        feudal_instructions: 'build blacksmith and range or stable',
        cup_instructions: '',
        castle_headers: [],
        castle_values: [],
        castle_instructions: '',
        eco: 'Don\'t need Houses (less wood)',
        team: 'Stables work faster',
        military: 'Cheaper Cav Archers',
        uu: 'Tarkan (Cavalry)',
        utech: 'Tarkans create at Stables, +100 yrs Relic victory, Spies costs less',
        opening: 'Scouts',
        transition: 'Archers',
        castle: 'Cav Archers + Halbs/Skirms',
        imp: 'Cav Archers + Trash + Siege',
        ...strategies.scouts_archers
    },
    japanese: { strategy: 'Meta',
        dark_headers: ['Sheep', 'Wood', 'Boar',
                       'Berries', 'Boar to farms', 'Wood'],
        dark_values: [6, 4, 2, 4, 1, '5 (9)'],
        dark_instructions: '',
        fup_instructions: 'While advancing: 2 sheep to wood (11), 3 to gold; build 1 barracks',
        feudal_headers: ['Gold', 'Farms', 'Wheelbarrow'],
        feudal_values: ['5 (8)', '10 (18)', '+'],
        feudal_instructions: 'build 2 ranges then blacksmith',
        cup_instructions: '',
        castle_headers: [],
        castle_values: [],
        castle_instructions: '',
        eco: 'Fish ships faster & tanky, Mining/Mill/Lumber cheaper',
        team: 'Galleys extra LOS',
        military: 'Infantry attack faster',
        uu: 'Samurai (Infantry)',
        utech: 'Towers extra arrows, Treps pack attack and move faster',
        opening: 'Man-At-Arms',
        transition: 'Archers/Skirms',
        castle: 'Archers + Skirm/Light Cav',
        imp: 'Trebs + Archers + Trash',
        ...strategies.maa_archers
    },
    magyars: { strategy: 'Meta',
        dark_headers: ['Sheep', 'Wood', 'Boar', 'Berries', 'Boar to farms', 'Wood'],
        dark_values: [6, 3, 2, 4, 2, '4 (7)'],
        dark_instructions: '',
        fup_instructions: 'On advance move 3 sheep to wood (10); build barracks',
        feudal_headers: ['Farms', 'Gold', 'Wheelbarrow', 'Farms'],
        feudal_values: ['8 (14)', '6 (+2 from berries)', '+', '2 (18)'],
        feudal_instructions: 'build stable, then 2 ranges and Blacksmith',
        cup_instructions: '',
        castle_headers: [],
        castle_values: [],
        castle_instructions: '',
        eco: 'Vills kills animals quickly',
        team: 'Archers +2 LOs',
        military: 'Forging line free, Scout Cav line cheaper',
        uu: 'Magyar Hussar',
        utech: 'Cav Archers +1 att&rng, Magyar Huszars cost no gold',
        opening: 'Scouts',
        transition: 'Archers',
        castle: 'Cav Archer + Light Cav',
        imp: 'Cav Archer + Light Cav + Treb',
        ...strategies.scouts_archers
    },
    mayans: { strategy: 'Meta',
        dark_headers: ['Sheep', 'Wood', 'Boar', 'Berries', 'Boar to farms', 'Wood'],
        dark_values: [6, 4, 2, 4, 1, '5 (9)'],
        dark_instructions: '',
        fup_instructions: 'While advancing: 2 sheep to wood (11), 3 to gold; build 1 barracks',
        feudal_headers: ['Gold', 'Farms', 'Wheelbarrow'],
        feudal_values: ['5 (8)', '10 (18)', '+'],
        feudal_instructions: 'build 2 ranges then blacksmith',
        cup_instructions: '',
        castle_headers: [],
        castle_values: [],
        castle_instructions: '',
        eco: 'start +1 vill, resources last 15% longer',
        team: 'Walls cheaper',
        military: 'Std archers cheaper',
        uu: 'Plumed Archer',
        utech: 'Std Archers +6 att vs buildings, Eagles +40HP',
        opening: 'Man-At-Arms',
        transition: 'Archers',
        castle: 'Archers + Skirms',
        imp: 'Eagles (tech) + Treb/Ram + Archer',
        ...strategies.maa_archers
    },
    mongols: { strategy: '19-pop scouts to skirms; castle age cav archers/light cav; imp rams/champs',
        dark_headers: ['Sheep', 'Wood', 'Boar', 'Deer to berries', 'Boar/sheep'],
        dark_values: [6, 3, 2, 4, '3 (11)'],
        dark_instructions: '',
        fup_instructions: 'On advance move 5 sheep to wood (8); build barracks',
        feudal_headers: [],
        feudal_values: [],
        feudal_instructions: '<h4>Feudal Age</h4>build stable',
        cup_instructions: '',
        castle_headers: [],
        castle_values: [],
        castle_instructions: '',
        eco: 'Hunters work faster',
        team: 'Scout Cav +2 LOS',
        military: 'Cav Archers fire faster, Light Cav extra HP',
        uu: 'Mangudai (Cav Archer)',
        utech: 'Houses keep pop space if destroyed, Siege moves faster',
        opening: 'Scouts',
        transition: 'Archers/Skirms',
        castle: 'Knights + Skirms',
        imp: 'Mangudai + Trash + Treb/Ram'
    },
    persians: { strategy: 'Meta',
        dark_headers: ['Sheep', 'Wood', 'Boar', 'Berries', 'Boar to farms', 'Wood'],
        dark_values: [6, 3, 2, 4, 2, '3 (7)'],
        dark_instructions: '',
        fup_instructions: 'While advancing: 3 sheep to wood, build 1 barracks',
        feudal_headers: ['Farms', 'Gold', 'Farms', 'Wheelbarrow'],
        feudal_values: ['8 (14)', '4 (6)', '1 (15)', '+'],
        feudal_instructions: 'build stable with 2 vills; after farms build Blacksmith, move 2 berries to gold',
        cup_instructions: 'While advancing, build second stable',
        castle_headers: [],
        castle_values: [],
        castle_instructions: '',
        eco: 'Start with +50 Wood/Food, TC + Dock more HP, TC faster',
        team: 'Knights +2 attack vs Archers',
        military: 'Knights +2 attack vs Archers',
        uu: 'War Elephant (Cavalry)',
        utech: 'Archers only cost wood, War Elephants faster',
        opening: 'Scouts',
        transition: 'Archers/Skirms',
        castle: 'Get relics + Knights + Skirms',
        imp: 'Trashbow + Hussar + Treb/Ram',
        ...strategies.scouts_archers
    },
    slavs: { strategy: 'Man-at-arms rush with 2 barracks, followed by mangonels or rams; monks/mangonels/rams; hussars post imp',
        dark_headers: ['Sheep', 'Wood', 'Boar', 'Berries', 'Boar to farms', 'Barracks', 'Gold'],
        dark_values: [6, 4, 2, 4, 2, 1, 2],
        dark_instructions: '',
        fup_instructions: 'While advancing: 3 sheep to wood, build another barracks',
        feudal_headers: ['Farms'],
        feudal_values: ['+'],
        feudal_instructions: '',
        cup_instructions: '',
        castle_headers: [],
        castle_values: [],
        castle_instructions: '',
        eco: 'Farms work faster',
        team: 'Military buildings +5 pop',
        military: 'Supplies is free, Siege cheaper',
        uu: 'Boyar',
        utech: 'Monks +3/+3 armour, Infantry spash damage',
        opening: 'Scouts',
        transition: 'Skirms',
        castle: 'Knights + Skirm',
        imp: 'Champions + Cav + Ram/Treb'
    }
};
var allCivs = [
    'Aztecs', 'Berbers', 'Britons', 'Burmese', 'Byzantines', 'Celts', 'Chinese', 'Ethiopians', 'Franks', 'Goths', 'Huns', 'Incas', 'Indians', 'Italians', 'Japanese', 'Khmer', 'Koreans', 'Magyars', 'Malay', 'Malians', 'Mayans', 'Mongols', 'Persians', 'Portuguese', 'Saracens', 'Slavs', 'Spanish', 'Teutons', 'Turks', 'Vietnamese', 'Vikings',
];
