var base_strategy = { strategy: "Meta",
                      dark_headers: [],
                      dark_values: [],
                      dark_instructions: "",
                      fup_instructions: "",
                      feudal_headers: [],
                      feudal_values: [],
                      feudal_instructions: "",
                      cup_instructions: "",
                      castle_headers: [],
                      castle_values: [],
                      castle_instructions: "",
                      opening: "",
                      transition: "",
                      castle: "",
                      imp: "",
                      important_techs: "",
                      bonuses: "",
                      uniques: "",
                      production: ""
                    };

var base_strategies = {
  eagles_castle: {...base_strategy,
                  strategy: "Eagles into Castle",
                  dark_headers: ["Sheep", "Wood", "Boar", "Berries", "Boar to farms", "Wood"],
                  dark_values: [6, 4, 2, 4, 2, "3 (7)", "4 sheep to gold, 2 barracks"],
                  fup_instructions: "4 sheep to gold, 2 barracks",
                  feudal_headers: ["Wood", "Gold", "Farms"],
                  feudal_values: ["3 (10)", "2 (4)", "+"],
                  feudal_instructions: "Blacksmith, Market",
                  opening: "Eagles",
                  transition: "Castle",
                 },
  maa_archers: {...base_strategy,
                strategy: "Man-at-Arms into Archers",
                dark_headers: ["Sheep", "Wood", "Boar", "Berries", "Boar/sheep", "Build", "Gold"],
                dark_values: [6, 4, 2, 4, "2 (10)", "Barracks to wood", 2],
                fup_instructions: "2 sheep to wood, berries, farms",
                feudal_headers: ["Wood", "Gold", "Farms", "Wheelbarrow"],
                feudal_values: ["5 (12)", "6 (8)", "16 (18)", "+"],
                feudal_instructions: "2 Ranges, Blacksmith",
                opening: "Men-at-Arms",
                transition: "Archers",
               },
  maa_scouts: {...base_strategy,
               strategy: "Man-at-Arms into Scouts",
               dark_headers: ["Sheep", "Wood", "Boar", "Berries", "Boar/sheep", "Build", "Gold", "Wood"],
               dark_values: [6, 4, 2, 4, "2 (10)", "Barracks to wood", "Mine 10 -> Wood", 1],
               fup_instructions: "4 sheep to wood, 2 to farms",
               feudal_headers: ["Farms", "Gold", "Farms", "Wheelbarrow"],
               feudal_values: ["8 (14)", "4 (6)", "2 (16)", "+"],
               feudal_instructions: "Stable, Blacksmith",
               opening: "Men-at-Arms",
               transition: "Scouts",
              },
  scouts_archers: {...base_strategy,
                   strategy: "Scouts into Archers",
                   dark_headers: ["Sheep", "Wood", "Boar", "Berries", "Boar to farms", "Wood"],
                   dark_values: [6, 3, 2, 4, 2, "4 (7)"],
                   fup_instructions: "3 sheep to wood (10); barracks",
                   feudal_headers: ["Farms", "Gold", "Wheelbarrow", "Farms"],
                   feudal_values: ["8 (14)", "6 (8)", "+", "2 (18)"],
                   feudal_instructions: "Stable, 2 Ranges, Blacksmith",
                   opening: "Scouts",
                   transition: "Archers",
                  },
  scouts_castle: {...base_strategy,
                  strategy: "Scouts into Castle",
                  dark_headers: ["Sheep", "Wood", "Boar", "Berries", "Boar to farms", "Wood"],
                  dark_values: [6, 3, 2, 4, 2, "4 (7)"],
                  fup_instructions: "3 sheep to wood (10); barracks",
                  feudal_headers: ["Farms", "Gold", "Farms", "Wheelbarrow"],
                  feudal_values: ["8 (14)", "4 (6)", "2 (16)", "+"],
                  feudal_instructions: "Stable, Blacksmith",
                  opening: "Scouts",
                  transition: "Castle",
                 },
};

var castle_strategies  = {
  eagles_pikes: {
    castle: "Eagles+Pikes",
    cup_instructions: "3rd Barracks",
  },
  light_cav_cav_archers: {
    castle: "LtCav+CavArchers",
    cup_instructions: "2nd Stable",
  },
  light_cav_xbow_or_knights_skirms: {
    castle: "Xbow+LtCav||Knights+skirms",
    cup_instructions: "2nd Stable",
  },
  knights_skirms: {
    castle: "Knights+skirms",
    cup_instructions: "2nd Stable",
  },
  xbow_light_cav: {
    castle: "Xbow+LtCav",
    cup_instructions: "2 Stables",
  },
  xbow_light_cav_pikes: {
    castle: "Xbow+(LtCav||Pikes)",
    cup_instructions: "2 Stables||2nd Barracks",
  },
};

var civs = ["aztecs", "berbers", "bohemians", "britons", "bulgarians", "burgundians", "burmese", "byzantines", "celts", "chinese", "cumans", "ethiopians", "franks", "goths", "huns", "incas", "indians", "italians", "japanese", "khmer", "koreans", "lithuanians", "magyars", "malay", "malians", "mayans", "mongols", "persians", "poles", "portuguese", "saracens", "sicilians", "spanish", "slavs", "tatars", "teutons", "turks", "vietnamese", "vikings"];

var strategies = {
  aztecs: {...base_strategies.eagles_castle, ...castle_strategies.eagles_pikes,
           imp: "Eagles + Trash + Siege",
           important_techs: "Garland Wars (Imp: 450F 750G)",
           bonuses: "Villagers carry +3<br>Military units created 11% faster<br>+5 Monk hit points for each Monastery technology<br>Start with +50 gold<br>Relics generate +33% gold",
           uniques: "Jaguar Warrior: infantry unit strong vs infantry<br><br>Atlatl: Skirmishers have +1 attack, +1 range.<br>Garland Wars: Infantry have +4 attack.",
           production: "<b>Archery Range</b><br>Attack: 3, Armor: 2, MISSING Thumb Ring<br>Arbalester (28/39)<br>Skirmisher (22/39)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Champion (1/39)<br>Pikeman (3/39)<br>Eagle Warrior (2/3)<br><b>Siege Workshop</b><br>Siege Engineers<br>Siege Ram (5/39)<br>Siege Onager (7/39)<br>Scorpion (25/39)",
          },
  berbers: {...base_strategies.scouts_archers, ...castle_strategies.knights_skirms,
            bonuses: "Villagers move 10% faster<br>Stable units cost -15% in Castle, -20% in Imperial Age<br>Ships move 10% faster<br>Genitour available in the Archery Range starting in the Castle Age",
            uniques: "Camel Archer: mounted archer<br><br>Kasbah: Team castles work 25% faster.<br>Maghrebi Camels: Camel troops regenerate.",
            production: "<b>Archery Range</b><br>Attack: 3, Armor: 3<br>Crossbowman (23/39)<br>Skirmisher (9/39)<br>Heavy Cavalry Archer (14/36)<br>Hand Cannoneer (8/20)<br>Genitour<br><b>Stable</b><br>Attack: 3, Armor: 3<br>Hussar (11/35)<br>Cavalier (16/35)<br>Camel Rider (4/12)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Champion (9/39)<br>Pikeman (34/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Capped Ram (24/39)<br>Onager (15/39)<br>Heavy Scorpion (8/39)<br>Bombard Cannon (5/21)",
           },
  bohemians: {...base_strategies.maa_archers,
              castle: "Xbow+Pikes, Hand Canonneers",
              cup_instructions: "2nd Barracks",
              bonuses: "Blacksmiths, Monasteries and Universities cost -100 wood<br>Chemistry and Hand Cannoneer available in Castle Age<br>Spearman-line deals +25% bonus damage<br>Fervor and Sanctity affect Villagers<br>Mining Camp technologies free<br>Markets work 80% faster",
              uniques: "Hussite Wagon: siege unit units behind it receive 50% less damage from incoming projectiles<br><br>Wagenburg Tactics: Gunpowder units move 15% faster.<br>Hussite Reforms: Monks and Monastery technologies have their gold cost replaced by food.",
              production: "<b>Archery Range</b><br>Attack: 3, Armor: 3, MISSING Thumb Ring, MISSING Bloodlines<br>Arbalester (17/39)<br>Skirmisher (21/39)<br>Hand Cannoneer (1/20)<br><b>Stable</b><br>Attack: 3, Armor: 2, MISSING Bloodlines<br>Light Cavalry (32/35)<br>Cavalier (30/35)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Champion (9/39)<br>Halberdier (8/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Capped Ram (24/39)<br>Onager (15/39)<br>Heavy Scorpion (8/39)<br>Houfnice",

             },
  britons: {...base_strategies.maa_archers, ...castle_strategies.xbow_light_cav_pikes,
            dark_values: [5, 4, 3, 4, "1 (9)", 1, 2],
            imp: "Archers + Trebs + Trash",
            important_techs: "Yeoman (Castle: 750W 450G)",
            bonuses: "Town Centers cost -50% wood starting in the Castle Age<br>Foot archers (except skirmishers) +1 range in Castle and Imperial Age (+2 total)<br>Shepherds work 25% faster<br>Archery Ranges work 20% faster",
            uniques: "Longbowman: archer with very long range<br><br>Yeomen: Foot archers have +1 range; towers have +2 attack.<br>Warwolf: Improves your Trebuchets by giving them blast damage.",
            production: "<b>Archery Range</b><br>Attack: 3, Armor: 3, MISSING Thumb Ring, MISSING Bloodlines<br>Arbalester (2/39)<br>Skirmisher (20/39)<br>Heavy Cavalry Archer (26/36)<br><b>Stable</b><br>Attack: 3, Armor: 3, MISSING Bloodlines<br>Light Cavalry (26/35)<br>Cavalier (25/35)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Champion (9/39)<br>Halberdier (9/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Capped Ram (24/39)<br>Onager (15/39)<br>Heavy Scorpion (8/39)",
           },
  bulgarians: {...base_strategies.maa_scouts,
               castle: "LtCav+CavArchers||Knights+Skirms",
               cup_instructions: "2nd Stable, Range",
               imp: "Champs with Bagains",
               important_techs: "Stirrups (Castle: (400F 200G); Bagains (Imp: (900F 450G)",
               bonuses: "Militia-line upgrades free<br>Town Centers cost -50% stone<br>Blacksmith and Siege Workshop technologies cost -50% food<br>Can build Krepost<br>Blacksmiths work 80% faster",
               uniques: "Konnik: cavalry unit that fights on as infantry when felled<br><br>Stirrups: Cavalry attack 33% faster.<br>Bagains: Militia-line receives +5 melee armor.",
               production: "<b>Archery Range</b><br>Attack: 3, Armor: 2, Parthian Tactics<br>Skirmisher (23/39)<br>Heavy Cavalry Archer (11/36)<br>MISSING Crossbowman<br><b>Stable</b><br>Attack: 3, Armor: 3<br>Hussar (10/35)<br>Cavalier (15/35)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Two-Handed Swordsman (22/39)<br>Halberdier (9/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Siege Ram (7/39)<br>Siege Onager (8/39)<br>Heavy Scorpion (8/39)",
              },
  burgundians: {...base_strategies.scouts_archers, ...castle_strategies.knights_skirms,
                castle: "Cavalier+skirm",
                bonuses: "Economic upgrades available one age earlier and cost -50% food<br>Stable technologies cost -50%<br>Cavalier upgrade available in Castle Age<br>Gunpowder units +25% attack<br>Relics generate both Gold & Food",
                uniques: "Coustillier: cavalry unit which can charge its attack<br><br>Burgundian Vineyards: Farmers slowly generate gold in addition to food.<br>Flemish Revolution: Upgrades all existing Villagers to Flemish Militia and allows Flemish Militia to be created at the Town Center.",
                production: "<b>Archery Range</b><br>Attack: 3, Armor: 2, MISSING Thumb Ring, MISSING Bloodlines<br>Crossbowman (32/39)<br>Skirmisher (32/39)<br>Cavalry Archer (36/36)<br>Hand Cannoneer (19/20)<br><b>Stable</b><br>Attack: 3, Armor: 3, MISSING Bloodlines<br>Hussar (22/35)<br>Paladin (7/35)<br><b>Barracks</b><br>Attack: 3, Armor: 3, MISSING Supplies<br>Champion (23/39)<br>Halberdier (9/39)<br><b>Siege Workshop</b><br>Capped Ram (35/39)<br>Onager (28/39)<br>Scorpion (31/39)<br>Bombard Cannon (13/21)",
               },
  burmese: {...base_strategies.scouts_castle,
            castle: "LtCav+Longswords||Elephant+Pikes",
            cup_instructions: "2nd Stable||2nd Barracks",
            imp: "Elite Elephants or Champions; Faith",
            important_techs: "Howdah (if elephants; Castle: 400F 300W)",
            bonuses: "Lumber Camp technologies free<br>Infantry +1 attack per age (starting in the Feudal Age)<br>Monastery technologies cost -50%<br>Relics visible on the map at the start of the game",
            uniques: "Arambai: cavalry archer with a powerful but inaccurate dart attack<br><br>Howdah: Battle Elephants receive +1 normal/+2 pierce armor.<br>Manipur Cavalry: Cavalry and Arambai deal +6 bonus attack vs buildings.",
            production: "<b>Archery Range</b><br>Attack: 3, Armor: 1, Parthian Tactics, MISSING Thumb Ring<br>Crossbowman (36/39)<br>Skirmisher (37/39)<br>Heavy Cavalry Archer (24/36)<br><b>Stable</b><br>Attack: 3, Armor: 3<br>Hussar (7/35)<br>Cavalier (14/35)<br>Battle Elephant (2/4)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Champion (3/39)<br>Halberdier (1/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Capped Ram (24/39)<br>Onager (15/39)<br>Heavy Scorpion (8/39)<br>Bombard Cannon (5/21)",
           },
  byzantines: {...base_strategies.scouts_archers,
               castle: "Xbow+Pikes||Camels+skirms",
               cup_instructions: "2nd Barracks",
               imp: "Adapt",
               bonuses: "Buildings +10% HPs Dark, +20% Feudal, +30% Castle, +40% Imperial Age<br>Camel Riders, Skirmishers, Pikemen, Halberdiers cost -25%<br>Fire ships attack 25% faster<br>Advance to Imperial Age costs -33%<br>Town Watch, Town Patrol free<br>Monks +50% heal speed",
               uniques: "Cataphract: cavalry unit strong vs infantry<br><br>Greek Fire: Fire Ships have +1 range.<br>Logistica: Cataphracts cause trample damage.",
               production: "<b>Archery Range</b><br>Attack: 3, Armor: 3, MISSING Bloodlines<br>Arbalester (9/39)<br>Skirmisher (5/39)<br>Heavy Cavalry Archer (19/36)<br>Hand Cannoneer (8/20)<br><b>Stable</b><br>Attack: 2, Armor: 3, MISSING Bloodlines<br>Hussar (26/35)<br>Paladin (12/35)<br>Camel Rider (11/12)<br><b>Barracks</b><br>Attack: 2, Armor: 3<br>Champion (27/39)<br>Halberdier (25/39)<br><b>Siege Workshop</b><br>Siege Ram (14/39)<br>Onager (28/39)<br>Scorpion (31/39)<br>Bombard Cannon (15/21)",
              },
  celts: {...base_strategies.maa_archers,
          dark_values: [6, 3, 2, 4, "2 (10)", 1, 2],
          castle: "Xbow+Pikes+Siege",
          cup_instructions: "2nd Barracks",
          imp: "Halbs + Siege + Woads",
          important_techs: "Furor Celtica (Imp: 750F 450G)",
          bonuses: "Infantry move 15% faster (starting in the Feudal Age)<br>Lumberjacks work 15% faster<br>Siege weapons fire 25% faster<br>Can steal sheep, and sheep within one Celt unit's LoS cannot be stolen<br>Siege Workshops work 20% faster",
          uniques: "Woad Raider: infantry unit fast-moving<br><br>Stronghold: Makes your castles and towers stronger by making them fire 25% faster.<br>Furor Celtica: Siege Workshop units have +40% hit points.",
          production: "<b>Archery Range</b><br>Attack: 2, Armor: 2, MISSING Thumb Ring, MISSING Bloodlines<br>Crossbowman (36/39)<br>Skirmisher (37/39)<br>Heavy Cavalry Archer (31/36)<br><b>Stable</b><br>Attack: 3, Armor: 2, MISSING Bloodlines<br>Hussar (26/35)<br>Paladin (12/35)<br><b>Barracks</b><br>Attack: 3, Armor: 3, MISSING Squires<br>Champion (21/39)<br>Halberdier (22/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Siege Ram (1/39)<br>Siege Onager (1/39)<br>Heavy Scorpion (2/39)",
         },
  chinese: {...base_strategies.scouts_archers, ...castle_strategies.light_cav_xbow_or_knights_skirms,
            dark_headers: ["Loom", "Sheep", "Wood", "Boar", "Berries", "Boar to farms", "Wood"],
            dark_values: ["+", 7, 3, 1, 4, 2, "4 (7)"],
            imp: "Chu Ko Nu + Trash + Rams/Trebs",
            bonuses: "Start with +3 villagers, -50 wood, -200 food<br>Technologies cost -10% Feudal, -15% Castle, -20% Imperial Age<br>Town Centers support 10 population and +5 LOS<br>Demolition ships +50% hit points<br>Farms +10% food",
            uniques: "Chu Ko Nu: archer with rapid-fire attack<br><br>Great Wall: Makes your walls and towers stronger by giving them +30% hit points.<br>Rocketry: Chu Ko Nu have +2 piercing attack; scorpions have +4 piercing attack.",
            production: "<b>Archery Range</b><br>Attack: 3, Armor: 3<br>Arbalester (9/39)<br>Skirmisher (9/39)<br>Heavy Cavalry Archer (14/36)<br><b>Stable</b><br>Attack: 3, Armor: 3<br>Light Cavalry (22/35)<br>Cavalier (19/35)<br>Camel Rider (6/12)<br><b>Barracks</b><br>Attack: 3, Armor: 3, MISSING Supplies<br>Champion (23/39)<br>Halberdier (9/39)<br><b>Siege Workshop</b><br>Siege Ram (14/39)<br>Onager (28/39)<br>Heavy Scorpion (3/39)",
           },
  cumans: {...base_strategy, ...castle_strategies.light_cav_cav_archers,
           strategy: "2 TC boom to scouts",
           dark_headers: ["Sheep", "Wood", "Boar", "Berries", "Sheep/Boar", "Wood"],
           dark_values: [6, 4, 2, 4, 3, 1],
           fup_instructions: "Sheep to pallisade",
           feudal_headers: ["Wood", "Berries/Farm"],
           feudal_values: [3, "+"],
           feudal_instructions: "Barracks and stable after TC",
           opening: "2nd TC",
           transition: "Scouts",
           important_techs: "Steppe Husbandry (Castle: 200F 300W)",
           bonuses: "Additional Town Center can be built in the Feudal Age<br>Siege Workshop and Battering Ram available in the Feudal Age; Capped Ram upgrade available in Castle Age<br>Archery Ranges and Stables cost -100 wood<br>Cavalry 5% faster each age (starting in Feudal Age)<br>Palisade Walls +33% HP",
           uniques: "Kipchak: cavalry archer with rapid-fire attack<br><br>Steppe Husbandry: Light Cavalry, Steppe Lancers and Cavalry Archers trained 100% faster.<br>Cuman Mercenaries: Team receives 10 free Elite Kipchak in Castle.",
           production: "<b>Archery Range</b><br>Attack: 2, Armor: 3, Parthian Tactics, MISSING Husbandry<br>Crossbowman (29/39)<br>Skirmisher (23/39)<br>Heavy Cavalry Archer (8/36)<br><b>Stable</b><br>Attack: 3, Armor: 3, MISSING Husbandry<br>Hussar (9/35)<br>Paladin (10/35)<br>Camel Rider (9/12)<br>Steppe Lancer (3/3)<br><b>Barracks</b><br>Attack: 3, Armor: 3, MISSING Supplies<br>Champion (23/39)<br>Halberdier (9/39)<br><b>Siege Workshop</b><br>Siege Ram (2/39)<br>Siege Onager (11/39)<br>Scorpion (31/39)",
          },
  ethiopians: {...base_strategies.maa_archers, ...castle_strategies.xbow_light_cav_pikes,
               imp: "Siege with Torsion Engines",
               bonuses: "Archers fire 18% faster<br>Receive +100 gold, +100 food when advancing to the next age<br>Pikeman upgrade free<br>Towers and Outposts +3 line of sight",
               uniques: "Shotel Warrior: infantry with high attack and fast training speed<br><br>Royal Heirs: Shotel Warriors are created nearly instantly.<br>Torsion Engines: Siege workshop units blast radius increased.",
               production: "<b>Archery Range</b><br>Attack: 3, Armor: 3, MISSING Bloodlines<br>Arbalester (6/39)<br>Skirmisher (9/39)<br>Heavy Cavalry Archer (19/36)<br><b>Stable</b><br>Attack: 3, Armor: 2, MISSING Bloodlines<br>Hussar (26/35)<br>Cavalier (30/35)<br>Camel Rider (12/12)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Two-Handed Swordsman (34/39)<br>Halberdier (9/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Siege Ram (7/39)<br>Siege Onager (5/39)<br>Heavy Scorpion (8/39)<br>Bombard Cannon (4/21)",
              },
  franks: {...base_strategies.scouts_archers, ...castle_strategies.knights_skirms,
           imp: "Cav + Axemen + Trebs",
           important_techs: "Chivalry (Imp: (600W 500G)",
           bonuses: "Castles cost -25%<br>Cavalry +20% hit points starting in Feudal Age<br>Mill technologies free<br>Foragers work 15% faster<br>Knights +2 line of sight",
           uniques: "Throwing Axeman: infantry unit with ranged melee attack<br><br>Bearded Axe: Throwing Axemen have +1 range.<br>Chivalry: Increases the production speed of stables by +40%.",
           production: "<b>Archery Range</b><br>Attack: 2, Armor: 2, MISSING Thumb Ring, MISSING Bloodlines<br>Crossbowman (36/39)<br>Skirmisher (37/39)<br>Heavy Cavalry Archer (31/36)<br>Hand Cannoneer (20/20)<br><b>Stable</b><br>Attack: 3, Armor: 3, MISSING Bloodlines<br>Light Cavalry (11/35)<br>Paladin (3/35)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Champion (9/39)<br>Halberdier (9/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Capped Ram (24/39)<br>Onager (15/39)<br>Heavy Scorpion (8/39)<br>Bombard Cannon (5/21)",
          },
  goths: {...base_strategies.maa_archers,
          castle: "Xbow+Pike||Longsword+(skirms||pikes), Huskarls",
          cup_instructions: "2nd Barracks",
          imp: "Perfusion",
          important_techs: "Anarchy (Castle: 450F 250G), Perfusion (Imp: 400W 600G)",
          bonuses: "Infantry cost -20% in Dark, -25% in Feudal, -30% in Castle, -35% in Imperial Age<br>Infantry +1 attack vs. buildings per age (starting from Feudal Age)<br>Villagers +5 attack vs. wild boar; hunters carry +15 meat<br>Loom can be researched instantly<br>+10 population in Imperial Age<br>Barracks work 20% faster",
          uniques: "Huskarl: infantry unit with high pierce armor<br><br>Anarchy: Allows Huskarls to be created at the Barracks.<br>Perfusion: Barracks units are created 100% faster.",
          production: "<b>Archery Range</b><br>Attack: 3, Armor: 3, MISSING Thumb Ring<br>Crossbowman (29/39)<br>Skirmisher (23/39)<br>Heavy Cavalry Archer (19/36)<br>Hand Cannoneer (8/20)<br><b>Stable</b><br>Attack: 3, Armor: 2<br>Hussar (22/35)<br>Cavalier (25/35)<br><b>Barracks</b><br>Attack: 3, Armor: 2, MISSING Arson, MISSING Supplies<br>Champion (6/39)<br>Halberdier (5/39)<br><b>Siege Workshop</b><br>Capped Ram (35/39)<br>Onager (28/39)<br>Heavy Scorpion (21/39)<br>Bombard Cannon (15/21)",
         },
  huns: {...base_strategies.scouts_archers, ...castle_strategies.light_cav_cav_archers,
         imp: "Cav Archers + Trash + Siege",
         bonuses: "Do not need houses, but start with -100 wood<br>Cavalry Archers cost -10% Castle, -20% Imperial Age<br>Trebuchets +30% accuracy<br>Stables work 20% faster",
         uniques: "Tarkan: cavalry unit with attack bonus vs buildings<br><br>Marauders: Enables you to create Tarkans at Stables.<br>Atheism: Relic and Wonder victories take +100 years to complete; enemy relics generate -50% resources.",
         production: "<b>Archery Range</b><br>Attack: 3, Armor: 2, Parthian Tactics<br>Crossbowman (29/39)<br>Skirmisher (23/39)<br>Heavy Cavalry Archer (10/36)<br><b>Stable</b><br>Attack: 3, Armor: 3<br>Hussar (11/35)<br>Paladin (6/35)<br><b>Barracks</b><br>Attack: 3, Armor: 2, MISSING Supplies<br>Two-Handed Swordsman (36/39)<br>Halberdier (26/39)<br><b>Siege Workshop</b><br>Siege Ram (14/39)<br>Mangonel (38/39)<br>Scorpion (31/39)",
        },
  incas: {...base_strategies.maa_archers,
          alt: {...base_strategies.eagles_castle, ...castle_strategies.eagles_pikes,
                important_techs: "Fabric Shields (Imp: 600F 600G)",
               },
          castle: "Xbow+Pikes",
          cup_instructions: "2nd Barracks",
          bonuses: "Start with a free Llama<br>Villagers affected by Blacksmith upgrades starting in the Castle Age<br>Houses support 10 population<br>Buildings cost -15% stone<br>Farms built 100% faster",
          uniques: "Kamayuk: spearman with increased attack range<br><br>Andean Sling: Upgrades your skirmishers and slingers by removing their minimum range.<br>Fabric Shields: Kamayuks, Slingers, Eagles have +1 armor/+2 pierce armor.",
          production: "<b>Archery Range</b><br>Attack: 3, Armor: 3<br>Arbalester (9/39)<br>Skirmisher (3/39)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Champion (9/39)<br>Halberdier (9/39)<br>Eagle Warrior (3/3)<br><b>Siege Workshop</b><br>Siege Engineers<br>Siege Ram (7/39)<br>Onager (15/39)<br>Heavy Scorpion (8/39)",
         },
  indians: {...base_strategies.scouts_archers,
            castle: "LtCav+CavArchers||Camels+skirms",
            cup_instructions: "2nd Stable",
            imp: "Imperial Camels, hand cannons, and bombard cannons",
            bonuses: "Villagers cost -10% Dark, -15% Feudal, -20% Castle, -25% Imperial Age<br>Fishermen work 10% faster<br>Stable units +1P armor in Castle and Imperial Age (+2 total)<br>Camel units +4 attack vs. buildings",
            uniques: "Elephant Archer: mounted archer unit strong vs archers and infantry<br><br>Sultans: All gold income 10% faster (Trade, mines, relics).<br>Shatagni: Hand cannoneers have +1 range.",
            production: "<b>Archery Range</b><br>Attack: 3, Armor: 3, Parthian Tactics<br>Crossbowman (23/39)<br>Skirmisher (9/39)<br>Heavy Cavalry Archer (4/36)<br>Hand Cannoneer (4/20)<br><b>Stable</b><br>Attack: 3, Armor: 2<br>Hussar (15/35)<br>Imperial Camel Rider (2/12)<br>MISSING Knight<br><b>Barracks</b><br>Attack: 3, Armor: 2<br>Champion (27/39)<br>Halberdier (26/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Capped Ram (24/39)<br>Onager (15/39)<br>Scorpion (27/39)<br>Bombard Cannon (5/21)",
           },
  italians: {...base_strategies.scouts_archers, ...castle_strategies.light_cav_xbow_or_knights_skirms,
             imp: "Hand cannons and bombard cannons, maybe Condotierri",
             important_techs: "Pavise (Castle: 300F 150G)",
             bonuses: "Advancing to the next age costs -15%<br>Dock and University technologies cost -33%<br>Fishing Ships cost -15%<br>Gunpowder units cost -20%<br>Condottiero available in the Barracks in Imperial Age",
             uniques: "Genoese Crossbowman: archer. strong vs cavalry and infantry<br><br>Pavise: Foot Archers and Condottieri have +1 armor/+1 pierce armor.<br>Silk Road: Trade units cost -50%.",
             production: "<b>Archery Range</b><br>Attack: 3, Armor: 3<br>Arbalester (9/39)<br>Skirmisher (9/39)<br>Cavalry Archer (26/36)<br>Hand Cannoneer (6/20)<br><b>Stable</b><br>Attack: 3, Armor: 3<br>Hussar (15/35)<br>Cavalier (19/35)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Champion (9/39)<br>Pikeman (34/39)<br>Condottiero<br><b>Siege Workshop</b><br>Capped Ram (35/39)<br>Onager (28/39)<br>Scorpion (31/39)<br>Bombard Cannon (14/21)",
            },
  japanese: {...base_strategies.maa_archers, ...castle_strategies.xbow_light_cav_pikes,
             imp: "Trebs + Archers + Trash",
             bonuses: "Fishing Ships 2x hit points; +2P armor; work rate +5% Dark, +10% Feudal, +15% Castle, +20% Imperial Age<br>Mill, Lumber/Mining Camps cost -50%<br>Infantry attack 33% faster starting in Feudal Age<br>Galleys +50% line of sight",
             uniques: "Samurai: infantry unit with fast attack<br><br>Yasama: Makes your towers stronger by making them shoot extra arrows.<br>Kataparuto: Trebuchets fire and pack/unpack faster.",
             production: "<b>Archery Range</b><br>Attack: 3, Armor: 3, Parthian Tactics<br>Arbalester (9/39)<br>Skirmisher (9/39)<br>Heavy Cavalry Archer (4/36)<br>Hand Cannoneer (8/20)<br><b>Stable</b><br>Attack: 3, Armor: 2<br>Light Cavalry (26/35)<br>Cavalier (25/35)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Champion (7/39)<br>Halberdier (6/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Capped Ram (24/39)<br>Onager (15/39)<br>Heavy Scorpion (8/39)",
            },
  khmer: {...base_strategies.scouts_archers,
          fup_instructions: "3 sheep to wood; NO BARRACKS",
          castle: "Knights+skirms -> scorpions",
          cup_instructions: "2nd stable",
		  important_techs: "Tusk Swords (Castle: 400W 450G)",
          bonuses: "No buildings required to advance to the next age or to unlock other buildings<br>Farmers don't require Mills/Town Centers to drop off food<br>Battle Elephants move 10% faster<br>Villagers can garrison in Houses<br>Scorpions +1 range",
          uniques: "Ballista Elephant: elephant equipped with a scorpion<br><br>Tusk Swords: Battle Elephants receive +3 attack<br>Double Crossbow: Ballista Elephants and Scorpions fire two projectiles.",
          production: "<b>Archery Range</b><br>Attack: 3, Armor: 3, Parthian Tactics, MISSING Thumb Ring<br>Arbalester (18/39)<br>Skirmisher (23/39)<br>Heavy Cavalry Archer (11/36)<br>Hand Cannoneer (8/20)<br><b>Stable</b><br>Attack: 3, Armor: 3<br>Hussar (15/35)<br>Cavalier (19/35)<br>Battle Elephant (1/4)<br><b>Barracks</b><br>Attack: 3, Armor: 2, MISSING Squires, MISSING Supplies<br>Two-Handed Swordsman (37/39)<br>Halberdier (30/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Siege Ram (7/39)<br>Onager (15/39)<br>Heavy Scorpion (1/39)",
         },
  koreans: {...base_strategies.maa_archers, ...castle_strategies.xbow_light_cav,
            castle: "Xbow+LtCav, War Wagons",
            bonuses: "Villagers +3 line of sight<br>Stone miners work 20% faster<br>Tower upgrades free (Bombard Tower requires Chemistry)<br>Archer armor upgrades free<br>Military units (except siege weapons) cost -20% wood<br>Mangonel-line minimum range reduced",
            uniques: "War Wagon: cavalry archer unit strong vs infantry and archers<br><br>Eupseong: Watch Towers, Guard Towers and Keeps have +2 range.<br>Shinkichon: Mangonels, Onagers, and Siege Onagers have +1 range.",
            production: "<b>Archery Range</b><br>Attack: 3, Armor: 3, MISSING Bloodlines<br>Arbalester (7/39)<br>Skirmisher (8/39)<br>Heavy Cavalry Archer (18/36)<br>Hand Cannoneer (8/20)<br><b>Stable</b><br>Attack: 2, Armor: 2, MISSING Bloodlines<br>Hussar (32/35)<br>Cavalier (34/35)<br><b>Barracks</b><br>Attack: 2, Armor: 3<br>Champion (27/39)<br>Halberdier (26/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Capped Ram (24/39)<br>Siege Onager (2/39)<br>Scorpion (27/39)<br>Bombard Cannon (5/21)",
           },
  lithuanians: {...base_strategies.scouts_archers, ...castle_strategies.knights_skirms,
                important_techs: "Tower Shields (Imp: 500F 200G)",
                bonuses: "Start with +150 food<br>Spearman-line and Skirmishers move 10% faster<br>Each garrisoned relic gives +1 attack to Knights and Leitis (maximum +4)<br>Monasteries work 20% faster",
                uniques: "Leitis: cavalry unit with attack that ignores armor<br><br>Hill Forts: Town Centers receive +3 range.<br>Tower Shields: Pikemen and Skirmishers receive +2 pierce armor.",
                production: "<b>Archery Range</b><br>Attack: 3, Armor: 3<br>Crossbowman (23/39)<br>Skirmisher (3/39)<br>Heavy Cavalry Archer (14/36)<br>Hand Cannoneer (8/20)<br><b>Stable</b><br>Attack: 2, Armor: 3<br>Winged Hussar (3/35)<br>Paladin (4/35)<br><b>Barracks</b><br>Attack: 2, Armor: 2, MISSING Supplies<br>Champion (33/39)<br>Halberdier (32/39)<br><b>Siege Workshop</b><br>Capped Ram (35/39)<br>Onager (28/39)<br>Scorpion (31/39)<br>Bombard Cannon (15/21)",
               },
  magyars: {...base_strategies.scouts_archers, ...castle_strategies.light_cav_xbow_or_knights_skirms,
            imp: "Cav Archer + Light Cav + Treb",
            bonuses: "Villagers kill wolves with 1 strike<br>Forging, Iron Casting, Blast Furnace free<br>Scout Cavalry, Light Cavalry, Hussar cost -15%<br>Foot archers +2 line of sight",
            uniques: "Magyar Huszar: light cavalry unit strong vs siege weapons<br><br>Corvinian Army: Magyar Huszars cost no gold.<br>Recurve Bow: Cavalry archers have +1 range, +1 attack.",
            production: "<b>Archery Range</b><br>Attack: 3, Armor: 3, Parthian Tactics<br>Arbalester (4/39)<br>Skirmisher (7/39)<br>Heavy Cavalry Archer (3/36)<br><b>Stable</b><br>Attack: 3, Armor: 3<br>Hussar (14/35)<br>Paladin (7/35)<br><b>Barracks</b><br>Attack: 3, Armor: 2, MISSING Squires<br>Champion (31/39)<br>Halberdier (30/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Capped Ram (24/39)<br>Onager (15/39)<br>Heavy Scorpion (8/39)",
           },
  malay: {...base_strategies.maa_archers,
          castle: "Xbow+Pikes||(Longsword||Elephant)+skirms",
          cup_instructions: "2nd Barracks||Stable",
          imp: "Trashswords, karambits",
          important_techs: "Forced Levy (Imp: 850F 500G)",
          bonuses: "Advancing to the next age 66% faster<br>Fish Traps cost -33% and provide 3X food<br>Battle Elephants cost -30% in Castle, -40% in Imperial Age<br>Docks +100% line of sight",
          uniques: "Karambit Warrior: infantry unit cheap and only takes half a population unit strong in high numbers<br><br>Thalassocracy: Upgrades your Docks to Harbors, which fire arrows.<br>Forced Levy: Militia-line gold cost is replaced by additional food cost.",
          production: "<b>Archery Range</b><br>Attack: 3, Armor: 3, MISSING Bloodlines<br>Arbalester (9/39)<br>Skirmisher (9/39)<br>Cavalry Archer (29/36)<br><b>Stable</b><br>Attack: 3, Armor: 1, MISSING Bloodlines<br>Light Cavalry (35/35)<br>Cavalier (34/35)<br>Battle Elephant (4/4)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Two-Handed Swordsman (32/39)<br>Halberdier (9/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Capped Ram (24/39)<br>Onager (15/39)<br>Heavy Scorpion (8/39)<br>Bombard Cannon (5/21)",
         },
  malians: {...base_strategies.maa_archers, ...castle_strategies.xbow_light_cav,
            alt: {...base_strategies.scouts_archers, ...castle_strategies.light_cav_xbow_or_knights_skirms, important_techs: "Farimba (Imp: (650F 400G)",},
            important_techs: "Farimba (Imp: (650F 400G)",
            bonuses: "Buildings cost -15% wood<br>Barracks units +1P armor per age (starting from Feudal Age)<br>Gold Mines last 30% longer<br>Universities work 80% faster",
            uniques: "Gbeto: infantry unit with ranged melee attack<br><br>Tigui: Town Centers fire arrows.<br>Farimba: Cavalry +5 attack.",
            production: "<b>Archery Range</b><br>Attack: 2, Armor: 3<br>Arbalester (18/39)<br>Skirmisher (23/39)<br>Heavy Cavalry Archer (19/36)<br>Hand Cannoneer (8/20)<br><b>Stable</b><br>Attack: 2, Armor: 3<br>Light Cavalry (2/35)<br>Cavalier (5/35)<br>Camel Rider (1/12)<br><b>Barracks</b><br>Attack: 2, Armor: 3<br>Champion (4/39)<br>Pikeman (24/39)<br><b>Siege Workshop</b><br>Capped Ram (35/39)<br>Siege Onager (11/39)<br>Scorpion (31/39)<br>Bombard Cannon (15/21)",
           },
  mayans: {...base_strategies.maa_archers,
           castle: "Xbow+Pikes||Eagles/skirms",
           cup_instructions: "2nd Barracks",
           imp: "Eagles (tech) + Treb/Ram + Archer",
           important_techs: "El Dorado (Imp: 750F 450G)",
           bonuses: "Start with +1 villager, but -50 food<br>Resources last 15% longer<br>Archers cost -10% Feudal, -20% Castle, -30% Imperial Age<br>Walls cost -50%",
           uniques: "Plumed Archer: fast-moving archer<br><br>Hul'che Javelineers: Improves your Skirmishers by making them throw a second projectile.<br>El Dorado: Eagle Warriors have +40 hit points.",
           production: "<b>Archery Range</b><br>Attack: 3, Armor: 3<br>Arbalester (3/39)<br>Skirmisher (2/39)<br><b>Barracks</b><br>Attack: 3, Armor: 3, MISSING Supplies<br>Two-Handed Swordsman (35/39)<br>Halberdier (9/39)<br>Eagle Warrior (1/3)<br><b>Siege Workshop</b><br>Siege Ram (14/39)<br>Onager (28/39)<br>Heavy Scorpion (21/39)",
          },
  mongols: {...base_strategies.scouts_archers, ...castle_strategies.light_cav_cav_archers,
            strategy: "19-pop scouts; castle age cav archers/light cav; imp rams/champs",
            dark_headers: ["Sheep", "Wood", "Boar", "Deer to berries", "Boar/sheep"],
            dark_values: [6, 3, 2, 4, "3 (11)"],
            fup_instructions: "5 sheep to wood (8); barracks",
            imp: "Mangudai + Trash + Treb/Ram + Champions",
            bonuses: "Cavalry archers fire 25% faster<br>Light Cavalry, Hussars, Steppe Lancers +30% hit points<br>Hunters work 40% faster<br>Scout Cavalry, Light Cavalry, Hussar +2 line of sight",
            uniques: "Mangudai: cavalry archer with fast-firing attack<br><br>Nomads: Houses don't lose their population room when they are destroyed.<br>Drill: Siege Workshop units move 50% faster.",
            production: "<b>Archery Range</b><br>Attack: 3, Armor: 2, Parthian Tactics<br>Arbalester (18/39)<br>Skirmisher (23/39)<br>Heavy Cavalry Archer (9/36)<br><b>Stable</b><br>Attack: 3, Armor: 2<br>Hussar (6/35)<br>Cavalier (25/35)<br>Camel Rider (10/12)<br>Steppe Lancer (2/3)<br><b>Barracks</b><br>Attack: 3, Armor: 3, MISSING Supplies<br>Champion (23/39)<br>Pikeman (34/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Siege Ram (3/39)<br>Siege Onager (4/39)<br>Heavy Scorpion (5/39)",
           },
  persians: {...base_strategies.scouts_archers, ...castle_strategies.knights_skirms,
             imp: "Trashbow + Hussar + Treb/Ram",
             important_techs: "Kamandaran (Castle: 400F 300G)",
             bonuses: "Start with +50 wood, food<br>Town Center, Dock 2x hit points; work rate +10% Feudal, +15% Castle, +20% Imperial Age<br>Knights +2 attack vs. Archers",
             uniques: "War Elephant: slow and powerful cavalry. strong vs buildings and units at close range<br><br>Kamandaran: Archer-line gold cost is replaced by additional wood cost.<br>Mahouts: War Elephants move 30% faster.",
             production: "<b>Archery Range</b><br>Attack: 2, Armor: 3, Parthian Tactics<br>Crossbowman (23/39)<br>Skirmisher (23/39)<br>Heavy Cavalry Archer (11/36)<br>Hand Cannoneer (8/20)<br><b>Stable</b><br>Attack: 3, Armor: 3<br>Hussar (15/35)<br>Paladin (1/35)<br>Camel Rider (6/12)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Halberdier (9/39)<br>MISSING Two-Handed Swordsman<br><b>Siege Workshop</b><br>Siege Ram (14/39)<br>Onager (28/39)<br>Heavy Scorpion (21/39)<br>Bombard Cannon (15/21)",
            },
  poles: {...base_strategies.scouts_archers, ...castle_strategies.knights_skirms,
          important_techs: "Szlachta Privileges (Castle: 500F 300G)",
          bonuses: "Villagers regenerate 5 HPs per minute in Dark, 10 in Feudal, 15 in Castle, 20 in Imperial Age<br>Folwark replaces Mill<br>Stone Miners generate gold in addition to stone<br>Scout Cavalry, Light Cavalry, Hussar +1 attack vs. Archers",
          uniques: "Obuch: infantry unit which can damage the armor of units it is fighting<br><br>Szlachta Privileges: Knights cost -60% gold.<br>Lechitic Legacy: Light Cavalry deals trample damage.",
          production: "<b>Archery Range</b><br>Attack: 3, Armor: 2<br>Arbalester (18/39)<br>Skirmisher (23/39)<br>Heavy Cavalry Archer (19/36)<br><b>Stable</b><br>Attack: 3, Armor: 2<br>Winged Hussar (1/35)<br>Cavalier (19/35)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Champion (9/39)<br>Pikeman (34/39)<br><b>Siege Workshop</b><br>Siege Ram (14/39)<br>Onager (28/39)<br>Scorpion (31/39)<br>Bombard Cannon (15/21)",
         },
  portuguese: {...base_strategies.maa_archers, ...castle_strategies.xbow_light_cav,
               imp: "Halberdiers, Hand Cannoneers, and Bombard Cannons",
               bonuses: "All units cost -20% gold<br>Technologies researched 30% faster<br>Ships +10% HP<br>Can build Feitoria in Imperial Age<br>Line of sight is shared with the team starting in the Dark Age",
               uniques: "Organ Gun: siege unit fires a volley of bullets<br><br>Carrack: Ships receive +1 normal/+1 pierce armor.<br>Arquebus: Ballistics for gunpowder units.",
               production: "<b>Archery Range</b><br>Attack: 3, Armor: 3<br>Arbalester (7/39)<br>Skirmisher (9/39)<br>Cavalry Archer (25/36)<br>Hand Cannoneer (3/20)<br><b>Stable</b><br>Attack: 3, Armor: 3<br>Light Cavalry (22/35)<br>Cavalier (17/35)<br><b>Barracks</b><br>Attack: 3, Armor: 3, MISSING Squires<br>Champion (9/39)<br>Halberdier (23/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Capped Ram (23/39)<br>Onager (14/39)<br>Scorpion (26/39)<br>Bombard Cannon (2/21)",
              },
  saracens: {...base_strategies.scouts_archers,
             castle: "Xbow+LtCav||Camels+skirms",
             cup_instructions: "2nd Stable",
             important_techs: "Zealotry (Imp: 500F 450G)",
             bonuses: "Market trade cost only 5%<br>Markets cost -100 wood<br>Transport Ships 2x hit points,<br>Galleys attack 25% faster<br>Camel units +10 hit points<br>Foot archers +2 attack vs. buildings",
             uniques: "Mameluke: camel unit with ranged melee attack<br><br>Madrasah: Killed monks return 33% of their cost.<br>Zealotry: Camel units have +20 hit points.",
             production: "<b>Archery Range</b><br>Attack: 3, Armor: 3, Parthian Tactics<br>Arbalester (4/39)<br>Skirmisher (9/39)<br>Heavy Cavalry Archer (4/36)<br>Hand Cannoneer (8/20)<br><b>Stable</b><br>Attack: 3, Armor: 3<br>Hussar (15/35)<br>Knight (33/35)<br>Camel Rider (3/12)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Champion (9/39)<br>Pikeman (34/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Siege Ram (7/39)<br>Siege Onager (8/39)<br>Scorpion (27/39)<br>Bombard Cannon (5/21)",
            },
  sicilians: {...base_strategies.scouts_archers, ...castle_strategies.light_cav_xbow_or_knights_skirms,
              important_techs: "Hauberk (Knights, Imp: 500F 400G)",
              bonuses: "Start with +100 stone<br>Castles and Town Centers built 100% faster<br>Land military units (except siege weapons) receive 50% less bonus damage<br>Farm upgrades provide +100% additional food<br>Donjon replaces Watch Tower-line<br>Transport Ships +5 line of sight and cost -50%",
              uniques: "Serjeant: infantry unit which can construct donjons<br><br>First Crusade: Each Town Center (maximum 5) spawns a one-time batch of 7 Serjeants. Units more resistant to conversion.<br>Hauberk: Knights receive +1 normal/+2 pierce armor.",
              production: "<b>Archery Range</b><br>Attack: 3, Armor: 2, MISSING Thumb Ring<br>Arbalester (9/39)<br>Skirmisher (32/39)<br>Cavalry Archer (31/36)<br><b>Stable</b><br>Attack: 3, Armor: 3<br>Light Cavalry (5/35)<br>Cavalier (11/35)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Champion (9/39)<br>Halberdier (9/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Siege Ram (7/39)<br>Siege Onager (8/39)<br>Heavy Scorpion (8/39)",
             },
  slavs: {...base_strategies.scouts_archers, ...castle_strategies.knights_skirms,
          imp: "Hussars",
          bonuses: "Farmers work 10% faster<br>Supplies free<br>Siege Workshop units 15% cheaper<br>Military buildings provide +5 population room",
          uniques: "Boyar: cavalry unit resistant to melee attack<br><br>Orthodoxy: Monks have extra armor.<br>Druzhina: Infantry damage adjacent units.",
          production: "<b>Archery Range</b><br>Attack: 2, Armor: 3, MISSING Thumb Ring<br>Crossbowman (32/39)<br>Skirmisher (32/39)<br>Heavy Cavalry Archer (26/36)<br><b>Stable</b><br>Attack: 3, Armor: 3<br>Hussar (15/35)<br>Cavalier (19/35)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Champion (8/39)<br>Halberdier (7/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Siege Ram (4/39)<br>Siege Onager (6/39)<br>Heavy Scorpion (7/39)",
         },
  spanish: {...base_strategies.scouts_castle, ...castle_strategies.knights_skirms,
            bonuses: "Builders work 30% faster<br>Blacksmith upgrades don't cost gold<br>Cannon Galleons benefit from Ballistics (fire faster, more accurately)<br>Gunpowder units fire 18% faster<br>Trade units generate +25% gold",
            uniques: "Conquistador: mounted hand cannoneer<br><br>Inquisition: Increases monk conversion rate.<br>Supremacy: Villagers have exceptional combat abilities.",
            production: "<b>Archery Range</b><br>Attack: 3, Armor: 3<br>Skirmisher (9/39)<br>Heavy Cavalry Archer (14/36)<br>Hand Cannoneer (7/20)<br>MISSING Crossbowman<br><b>Stable</b><br>Attack: 3, Armor: 3<br>Hussar (15/35)<br>Paladin (7/35)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Champion (9/39)<br>Halberdier (9/39)<br><b>Siege Workshop</b><br>Siege Ram (14/39)<br>Onager (28/39)<br>Scorpion (31/39)<br>Bombard Cannon (15/21)",
           },
  tatars: {...base_strategies.scouts_archers, ...castle_strategies.light_cav_cav_archers,
           important_techs: "Silk Armor (Castle: 400W 300G)",
           bonuses: "Villagers gather +50% food from herdables<br>New Town Centers spawn 2 Sheep starting in the Castle Age<br>Units deal +25% damage when fighting from higher elevation<br>Thumb Ring, Parthian Tactics free<br>Cavalry Archers +2 line of sight",
           uniques: "Keshik: cavalry unit that generates gold when fighting other units<br><br>Silk Armor: Light Cavalry, Steppe Lancers and Cavalry Archers receive +1 normal/+1 pierce armor.<br>Timurid Siegecraft: Trebuchets receive +2 range. Enables Flaming Camels.",
           production: "<b>Archery Range</b><br>Attack: 3, Armor: 3, Parthian Tactics<br>Crossbowman (22/39)<br>Skirmisher (5/39)<br>Heavy Cavalry Archer (1/36)<br>Hand Cannoneer (5/20)<br><b>Stable</b><br>Attack: 3, Armor: 3<br>Hussar (4/35)<br>Cavalier (17/35)<br>Camel Rider (5/12)<br>Steppe Lancer (1/3)<br><b>Barracks</b><br>Attack: 3, Armor: 1, MISSING Supplies<br>Two-Handed Swordsman (38/39)<br>Halberdier (33/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Siege Ram (6/39)<br>Onager (13/39)<br>Heavy Scorpion (6/39)",
          },
  teutons: {...base_strategies.scouts_archers, ...castle_strategies.knights_skirms,
            bonuses: "Monks healing range 2x<br>Towers garrison 2x units<br>Murder Holes, Herbal Medicine free<br>Farms cost -40%<br>Town Center garrison +10<br>Barracks and Stable units +1 armor in Castle and Imperial Age (+2 total)<br>Units resist conversion",
            uniques: "Teutonic Knight: infantry unit slow and powerful<br><br>Ironclad: Increases the armor of all siege weapons so they're more resistant to melee attack.<br>Crenellations: Castles have +3 range; garrisoned infantry fire arrows.",
            production: "<b>Archery Range</b><br>Attack: 2, Armor: 3, MISSING Thumb Ring, MISSING Husbandry<br>Crossbowman (32/39)<br>Skirmisher (32/39)<br>Cavalry Archer (35/36)<br>Hand Cannoneer (8/20)<br><b>Stable</b><br>Attack: 3, Armor: 3, MISSING Husbandry<br>Paladin (2/35)<br>MISSING Light Cavalry<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Champion (4/39)<br>Halberdier (2/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Capped Ram (22/39)<br>Siege Onager (3/39)<br>Heavy Scorpion (3/39)<br>Bombard Cannon (3/21)",
           },
  turks: {...base_strategies.scouts_archers, ...castle_strategies.light_cav_cav_archers,
          important_techs: "Sipahi (Castle: 350F 150G)",
          bonuses: "Gunpowder units +25% hit points; researching gunpowder technologies costs -50%; Chemistry free<br>Gold miners work 20% faster<br>Scout Cavalry, Light Cavalry, Hussar +1P armor<br>Light Cavalry and Hussar upgrades free<br>Gunpowder units created 25% faster",
          uniques: "Janissary: hand cannoneer with longer range and no minimum range<br><br>Sipahi: Cavalry archers have +20 hit points.<br>Artillery: Bombard Towers, Bombard Cannons, and Cannon Galleons have +2 range.",
          production: "<b>Archery Range</b><br>Attack: 3, Armor: 3, Parthian Tactics<br>Crossbowman (23/39)<br>Skirmisher (32/39)<br>Heavy Cavalry Archer (2/36)<br>Hand Cannoneer (2/20)<br>MISSING Elite Skirmisher<br><b>Stable</b><br>Attack: 3, Armor: 3<br>Hussar (8/35)<br>Cavalier (19/35)<br>Camel Rider (6/12)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Champion (9/39)<br>MISSING Pikeman<br><b>Siege Workshop</b><br>Siege Ram (14/39)<br>Mangonel (38/39)<br>Heavy Scorpion (21/39)<br>Bombard Cannon (1/21)",
         },
  vietnamese: {...base_strategies.maa_archers, ...castle_strategies.xbow_light_cav_pikes,
               important_techs: "Chatras (Elephants, 250F 250G)",
               bonuses: "Enemy positions are revealed at the start of the game<br>Economic upgrades cost no wood<br>Archery Range units +20% HP<br>Conscription free<br>Imperial Skirmisher upgrade available in the Imperial Age",
               uniques: "Rattan Archer: archer with high pierce armor<br><br>Chatras: Battle Elephants receive +100 HP.<br>Paper Money: You and all your allies receive +500 Gold.",
               production: "<b>Archery Range</b><br>Attack: 3, Armor: 3<br>Arbalester (1/39)<br>Imperial Skirmisher (1/39)<br>Heavy Cavalry Archer (4/36)<br><b>Stable</b><br>Attack: 2, Armor: 3<br>Light Cavalry (26/35)<br>Cavalier (25/35)<br>Battle Elephant (3/4)<br><b>Barracks</b><br>Attack: 2, Armor: 3<br>Champion (27/39)<br>Halberdier (26/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Capped Ram (24/39)<br>Onager (15/39)<br>Scorpion (27/39)<br>Bombard Cannon (5/21)",
              },
  vikings: {...base_strategies.maa_archers,
            castle: "Xbow+Pikes||Longswords+skirms",
            cup_instructions: "2nd Barracks",
            imp: "Champions",
            important_techs: "Chieftains (Castle: 700F 500G)",
            bonuses: "Warships cost -15% Feudal Age, -15% Castle Age, -20% Imperial Age<br>Infantry +10% hit points Feudal, +15% Castle, +20% Imperial Age<br>Wheelbarrow, Hand Cart free<br>Docks cost -15%",
            uniques: "Berserk: infantry unit that slowly heals itself<br><br>Chieftains: Infantry get attack bonus vs. cavalry.<br>Berserkergang: Berserks regenerate faster.",
            production: "<b>Archery Range</b><br>Attack: 3, Armor: 3, MISSING Bloodlines, MISSING Husbandry<br>Arbalester (9/39)<br>Skirmisher (9/39)<br>Cavalry Archer (30/36)<br><b>Stable</b><br>Attack: 3, Armor: 2, MISSING Bloodlines, MISSING Husbandry<br>Light Cavalry (34/35)<br>Cavalier (32/35)<br><b>Barracks</b><br>Attack: 3, Armor: 3<br>Champion (2/39)<br>Pikeman (4/39)<br><b>Siege Workshop</b><br>Siege Engineers<br>Siege Ram (7/39)<br>Onager (15/39)<br>Heavy Scorpion (8/39)",
           },
  water: {...base_strategy,
          strategy: "26-pop up to Fire Galleys",
          dark_headers: ["Sheep", "Wood", "Boar", "House -> Dock -> shorefish/houses", "Wood", "Boar/sheep"],
          dark_values: [6, 4, 1, 1, "2 (6)", "7 (14)"],
          dark_instructions: "Build 4 fishing ships with dock",
          fup_instructions: "While advancing: build 2nd dock, 8 sheep to wood, 4 sheep to gold, 2 sheep to stragglers",
          feudal_headers: ["Gold", "Berries"],
          feudal_values: ["2 (6)", "+"],
          feudal_instructions: "Double-bit axe; build 3rd dock; stragglers to sheep/berries",
          opening: "Fire Galleys",
          transition: "",
          castle: "War Galleys/Fire Ships",
         },
  hybrid: {...base_strategy,
           strategy: "26-pop up to Fire Galleys and Archers",
           dark_headers: ["Sheep", "Wood", "Boar", "House -> Dock -> shorefish/houses", "Wood", "Boar/sheep"],
           dark_values: [6, 4, 1, 1, "2 (6)", "7 (14)"],
           dark_instructions: "Build 4 fishing ships with dock",
           fup_instructions: "While advancing: build barracks and 2nd dock, 7 sheep to wood, 3 sheep to gold, 4 sheep to stragglers",
           feudal_headers: ["Gold", "Berries", "Farms", "Wheelbarrow"],
           feudal_values: ["4 (7)", 4, 14, "+"],
           feudal_instructions: "Double-bit axe; build 2 ranges, 3rd dock, blacksmith; stragglers to sheep/farms",
          }
};
