      var archers = [{p: 5, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, b: 1, hb: 2},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 4},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 5},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 1},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 2},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3, hb: 1},
{p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 7, lj: 4},
{p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4},
{p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 1},
{p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 2},
{p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 3},
{p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 4},
{p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3, fo: 4, fa: 1, hb: 1},
{p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 5, fo: 4, fa: 1},
{p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 6, fo: 4, fa: 1},
{p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 9, fo: 4, fa: 1, m: 3},
{p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 10, fo: 4, fa: 1, m: 3},
{p: 25, l: true, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 11, fo: 4, fa: 1, m: 3},
{p: 25, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 11, fo: 4, fa: 1, m: 3},
{p: 25, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 10, fo: 4, fa: 1, m: 3, b: 1},
{p: 25, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 10, fo: 4, fa: 1, m: 3, hb: 1},
{p: 30, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 9, fo: 4, fa: 1, m: 4, b: 2},
{p: 30, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 9, fo: 4, fa: 1, m: 5, b: 2},
{p: 30, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 9, fo: 4, fa: 1, m: 6, b: 1, hb: 1},
{p: 35, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 9, fo: 4, fa: 1, m: 7, b: 1, hb: 1},
{p: 40, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: false, h: 0, lj: 10, fo: 0, fa: 8, m: 8, hb: 1},
{p: 45, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: false, h: 0, lj: 10, fo: 0, fa: 9, m: 8, hb: 1},
{p: 50, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: false, h: 0, lj: 10, fo: 0, fa: 10, m: 8, hb: 1},
{p: 55, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: false, h: 0, lj: 10, fo: 0, fa: 11, m: 8, hb: 1},
{p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: false, h: 0, lj: 10, fo: 0, fa: 13, m: 8},
{p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: false, h: 0, lj: 10, fo: 0, fa: 14, m: 8},
{p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: true, h: 0, lj: 10, fo: 0, fa: 14, m: 8},
{p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: true, h: 0, lj: 10, fo: 0, fa: 15, m: 8},
{p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: true, h: 0, lj: 10, fo: 0, fa: 16, m: 8},
{p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: true, h: 0, lj: 10, fo: 0, fa: 16, m: 8, hb: 1},
{p: 65, l: true, a: 'Castle', dba: true, hc: true, bs: false, fl: true, wb: true, h: 0, lj: 10, fo: 0, fa: 17, m: 8, hb: 1},
]
