var scouts = [{p: 5, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, b: 1, hb: 2},
              {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 4},
              {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 5},
              {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6},
              {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 1},
              {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 2},
              {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3},
              {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3, hb: 1},
              {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3},
              {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3, fo: 1},
              {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3, fo: 2},
              {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3, fo: 3},
              {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3, fo: 4},
              {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3, fo: 4, fa: 1},
              {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3, fo: 3, fa: 2, hb: 1},
              {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 4, fa: 2},
              {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 5, fo: 4, fa: 2},
              {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 6, fo: 4, fa: 2},
              {p: 25, l: true, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 7, fo: 4, fa: 2, message: '5th sheep done'},
              {p: 25, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 5, lj: 10, fo: 4, fa: 2},
              {p: 25, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 4, lj: 10, fo: 4, fa: 2, b: 1},
              {p: 25, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 4, lj: 10, fo: 4, fa: 2, hb: 1},
              {p: 30, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, h: 3, lj: 10, fo: 4, fa: 3, b: 2},
              {p: 30, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, h: 3, lj: 10, fo: 4, fa: 5, hb: 1},
              {p: 35, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, h: 3, lj: 10, fo: 4, fa: 6, hb: 1},
              {p: 40, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, h: 3, lj: 10, fo: 4, fa: 7, hb: 1, message: 'Sheep done'},
              {p: 45, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 10, fo: 4, fa: 11, hb: 1},
              {p: 50, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 10, fo: 4, fa: 12, hb: 1},
              {p: 55, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 10, fo: 4, fa: 13, hb: 1},
             ]
var archers = [{p: 5, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, b: 1, hb: 2, builderDone: true},
               {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 4},
               {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 5},
               {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6},
               {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 1},
               {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 2},
               {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3},
               {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3, hb: 1},
               {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 7, lj: 4},
               {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4},
               {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 1},
               {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 2},
               {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 3},
               {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 4},
               {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3, fo: 4, fa: 1, hb: 1},
               {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 5, fo: 4, fa: 1},
               {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 6, fo: 4, fa: 1, message: 'Boar done'},
               {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 9, fo: 4, fa: 1, m: 3},
               {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 10, fo: 4, fa: 1, m: 3},
               {p: 25, l: true, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 11, fo: 4, fa: 1, m: 3},
               {p: 25, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 11, fo: 4, fa: 1, m: 3},
               {p: 25, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 10, fo: 4, fa: 1, m: 3, b: 1, builderDone: true},
               {p: 25, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 10, fo: 4, fa: 1, m: 3, hb: 1},
               {p: 30, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 9, fo: 4, fa: 1, m: 4, b: 2},
               {p: 30, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 9, fo: 4, fa: 1, m: 5, b: 2, builderDone: true},
               {p: 30, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 9, fo: 4, fa: 1, m: 6, b: 1, hb: 1},
               {p: 35, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, h: 3, lj: 9, fo: 4, fa: 1, m: 7, b: 1, hb: 1, builderDone: true, message: 'Sheep done'},
               {p: 40, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: false, lj: 10, fo: 4, fa: 4, m: 8, hb: 1},
               {p: 45, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: false, lj: 10, fa: 5, fo: 4, m: 8, hb: 1, message: 'Berries done'},
               {p: 50, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: false, lj: 10, fa: 10, m: 8, hb: 1},
               {p: 55, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: false, lj: 10, fa: 11, m: 8, hb: 1},
               {p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: false, lj: 10, fa: 13, m: 8},
               {p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: true, lj: 10, fa: 14, m: 8},
               {p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: true, lj: 10, fa: 15, m: 8},
               {p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: true, lj: 10, fa: 16, m: 8},
               {p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: true, wb: true, lj: 10, fa: 16, m: 8, hb: 1},
               {p: 65, l: true, a: 'Castle', dba: true, hc: true, bs: false, fl: true, wb: true, lj: 10, fa: 17, m: 8, hb: 1},
              ]
var scoutArchers = scouts.concat({p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 9, fo: 2, fa: 14, b: 1, m: 3},
                                 {p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 9, fo: 2, fa: 14, builderDone: true, b: 1, m: 4},
                                 {p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 9, fo: 2, fa: 14, b: 1, m: 5},
                                 {p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 9, fo: 2, fa: 14, builderDone: true, b: 1, m: 6},
                                 {p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 9, fo: 2, fa: 14, hb: 1, m: 7},
                                 {p: 65, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: true, lj: 9, fo: 2, fa: 14, b: 1, m: 8, message: 'Berries done'},
                                 {p: 65, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: true, lj: 9, fa: 16, builderDone: true, b: 1, m: 8},
                                 {p: 65, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: true, lj: 10, fa: 17, m: 8},
                                 {p: 65, l: true, a: 'Castle', dba: true, hc: true, bs: false, fl: false, wb: true, lj: 10, fa: 18, m: 8},
                                )
var scoutSkirms =  scouts.concat({p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 10, fo: 4, fa: 14, b: 1},
                                 {p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 11, fo: 2, fa: 14, builderDone: true, b: 1, m: 2},
                                 {p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 12, fo: 2, fa: 14, b: 1, m: 2},
                                 {p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 12, fo: 2, fa: 14, builderDone: true, b: 1, m: 3},
                                 {p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: true, lj: 12, fo: 2, fa: 14, builderDone: true, b: 1, m: 4, message: 'Berries done'},
                                 {p: 60, l: true, a: 'Castle', dba: true, hc: true, bs: false, fl: false, wb: true, lj: 12, fa: 18, m: 4},
                                )
var scoutCastle = scouts.concat({p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 10, fo: 4, fa: 14, b: 1},
                                {p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 10, fo: 2, fa: 15, builderDone: true, b: 1, m: 2},
                                {p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 10, fo: 2, fa: 16, builderDone: true, b: 1, m: 2},
                                {p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 10, fo: 2, fa: 16, m: 4},
                                {p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: true, lj: 10, fo: 2, fa: 16, m: 5},
                                {p: 60, l: true, a: 'Castle', dba: true, hc: true, bs: false, fl: false, wb: true, lj: 10, fo: 2, fa: 16, m: 5},
                               )
var maaArchers = [{p: 5, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, b: 1, hb: 2, builderDone: true},
                  {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 4},
                  {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 5},
                  {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6},
                  {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 1},
                  {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 2},
                  {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3},
                  {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3, hb: 1},
                  {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 7, lj: 3, hb: 1},
                  {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4},
                  {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 1},
                  {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 2},
                  {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 3},
                  {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 4},
                  {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 9, lj: 4, fo: 4},
                  {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 9, lj: 4, fo: 4, b: 1},
                  {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 10, lj: 4, fo: 4, builderDone: true, b: 1},
                  {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 10, lj: 4, fo: 4, hb: 1, m: 1},
                  {p: 30, l: true, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 10, lj: 5, fo: 4, m: 2},
                  {p: 30, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 10, lj: 5, fo: 4, m: 2},
                  {p: 30, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 4, lj: 7, fo: 6, fa: 2, m: 2, message: 'Sheep done'},
                  {p: 30, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, lj: 12, fo: 6, fa: 2, m: 2},
                  {p: 30, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, lj: 12, fo: 4, b: 2, fa: 2, m: 3},
                  {p: 30, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, lj: 12, fo: 4, builderDone: true, b: 2, fa: 2, m: 4},
                  {p: 30, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, lj: 12, fo: 4, b: 1, hb: 1, fa: 2, m: 5},
                  {p: 35, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, lj: 12, fo: 4, builderDone: true, b: 1, hb: 1, fa: 2, m: 6},
                  {p: 40, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, fo: 4, hb: 1, fa: 2, m: 8, message: 'Berries done'},
                  {p: 45, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, hb: 1, fa: 7, m: 8},
                  {p: 50, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, hb: 1, fa: 8, m: 8},
                  {p: 55, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, hb: 1, fa: 9, m: 8},
                  {p: 60, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, hb: 1, fa: 10, m: 8},
                  {p: 65, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, hb: 1, fa: 11, m: 8},
                  {p: 70, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, fa: 13, m: 8},
                  {p: 70, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, fa: 14, m: 8},
                  {p: 70, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, fa: 15, m: 8},
                  {p: 70, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, fa: 16, m: 8},
                  {p: 70, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, fa: 17, m: 8},
                  {p: 70, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: true, lj: 12, fa: 18, m: 8},
                  {p: 70, l: true, a: 'Castle', dba: true, hc: false, bs: false, fl: true, wb: true, lj: 12, fa: 18, m: 8},
                 ]
var maaTowers = [{p: 5, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, b: 1, hb: 2, builderDone: true},
                 {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 4},
                 {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 5},
                 {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6},
                 {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 1},
                 {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 2},
                 {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3},
                 {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3, hb: 1},
                 {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 7, lj: 3, hb: 1},
                 {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4},
                 {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 1},
                 {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 2},
                 {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 3},
                 {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 4},
                 {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 9, lj: 4, fo: 4},
                 {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 9, lj: 4, fo: 4, b: 1},
                 {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 10, lj: 4, fo: 4, builderDone: true, b: 1},
                 {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 10, lj: 4, fo: 4, hb: 1, m: 1},
                 {p: 30, l: true, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 11, lj: 4, fo: 4, m: 2},
                 {p: 30, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 10, lj: 4, fo: 4, builderDone: true, b: 1, m: 2},
                 {p: 30, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 9, lj: 4, fo: 6, m: 2, message: '40g maa upgrade collected (nb: switch all gold to stone)'},
                 {p: 30, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, h: 1, lj: 4, fo: 6, m: 5, i: 5},
                ]
var fcBoom = [{p: 5, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, b: 1, hb: 2, builderDone: true},
              {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 4},
              {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 5},
              {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6},
              {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 1},
              {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 2},
              {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3},
              {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3, hb: 1},
              {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 7, lj: 4},
              {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4},
              {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 1},
              {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 2},
              {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 3},
              {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 4},
              {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3, fo: 4, fa: 1, hb: 1},
              {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 4, fa: 2},
              {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 5, fo: 4, fa: 2},
              {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 6, fo: 4, fa: 2},
              {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 7, fo: 4, fa: 2},
              {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 7, fo: 4, fa: 2, hb: 1},
              {p: 30, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 9, fo: 4, fa: 2},
              {p: 30, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 9, fo: 4, fa: 2, m: 1},
              {p: 30, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 9, fo: 4, fa: 2, m: 2},
              {p: 30, l: true, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 9, fo: 4, fa: 2, m: 3},
              {p: 30, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 9, fo: 4, fa: 2, m: 3, message: 'Sheep done'},
              {p: 30, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, lj: 9, fo: 6, fa: 8, m: 3},
              {p: 30, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, lj: 8, fo: 5, fa: 8, m: 3, b: 3},
              {p: 30, l: true, a: 'Castle', dba: false, hc: false, bs: false, fl: false, wb: false, lj: 9, fo: 5, fa: 8, m: 3, builderDone: true, b: 3},
              {p: 30, l: true, a: 'Castle', dba: false, hc: false, bs: false, fl: false, wb: false, lj: 14, fo: 3, fa: 8, m: 3},
              {p: 30, l: true, a: 'Castle', dba: false, hc: false, bs: false, fl: false, wb: false, lj: 14, fo: 2, fa: 8, m: 3, hb: 1},
             ]
var fcKnights = [{p: 5, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, b: 1, hb: 2, builderDone: true},
                 {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 4},
                 {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 5},
                 {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6},
                 {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 1},
                 {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 2},
                 {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3},
                 {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3, hb: 1},
                 {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 7, lj: 4},
                 {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4},
                 {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 1},
                 {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 2},
                 {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 3},
                 {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 4},
                 {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3, fo: 4, fa: 1, hb: 1},
                 {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 4, fa: 2},
                 {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 5, fo: 4, fa: 2},
                 {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 6, fo: 4, fa: 2},
                 {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 7, fo: 4, fa: 2},
                 {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 7, fo: 4, fa: 2, hb: 1},
                 {p: 30, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 9, fo: 4, fa: 2},
                 {p: 30, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 10, fo: 4, fa: 2},
                 {p: 30, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 10, fo: 4, fa: 2, m: 1},
                 {p: 30, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 10, fo: 4, fa: 2, m: 2},
                 {p: 30, l: true, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 10, fo: 4, fa: 2, m: 3},
                 {p: 30, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 10, fo: 4, fa: 2, m: 3, message: 'Sheep done'},
                 {p: 30, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, lj: 10, fo: 6, fa: 8, m: 3},
                 {p: 30, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, lj: 10, fo: 5, fa: 8, m: 3, builderDone: true, b: 1},
                 {p: 30, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, lj: 8, fo: 5, fa: 8, m: 4, b: 3},
                 {p: 30, l: true, a: 'Castle', dba: false, hc: false, bs: false, fl: false, wb: false, lj: 8, fo: 5, fa: 8, m: 5, builderDone: true, b: 3},
                 {p: 30, l: true, a: 'Castle', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 10, fo: 3, fa: 10, m: 6},
                 {p: 30, l: true, a: 'Castle', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 10, fo: 2, fa: 10, m: 6, builderDone: true, b: 1},
                 {p: 30, l: true, a: 'Castle', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 10, fo: 2, fa: 10, m: 6, hb: 1},
                ]
var fcUU = [{p: 5, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, b: 1, hb: 2, builderDone: true},
            {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 4},
            {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 5},
            {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6},
            {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 1},
            {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 2},
            {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3},
            {p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3, hb: 1},
            {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 7, lj: 4},
            {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4},
            {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 1},
            {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 2},
            {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 3},
            {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 4},
            {p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3, fo: 4, fa: 1, hb: 1},
            {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 4, fa: 2},
            {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 5, fo: 4, fa: 2},
            {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 6, fo: 4, fa: 2},
            {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 7, fo: 4, fa: 2},
            {p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 7, fo: 4, fa: 2, hb: 1},
            {p: 30, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 9, fo: 4, fa: 2},
            {p: 30, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 9, fo: 4, fa: 2, m: 1},
            {p: 30, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 9, fo: 4, fa: 2, m: 2, message: 'Next miners to stone'},
            {p: 30, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 9, fo: 4, fa: 2, m: 3},
            {p: 30, l: true, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 9, fo: 4, fa: 2, m: 4},
            {p: 30, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 9, fo: 4, fa: 2, m: 4, message: 'Sheep done'},
            {p: 30, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, lj: 9, fo: 4, fa: 8, m: 6},
            {p: 30, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, lj: 7, fo: 3, fa: 8, m: 7, b: 3},
            {p: 30, l: true, a: 'Castle', dba: false, hc: false, bs: false, fl: false, wb: false, lj: 7, fo: 3, fa: 8, m: 8, builderDone: true, b: 3},
            {p: 30, l: true, a: 'Castle', dba: false, hc: false, bs: false, fl: false, wb: false, lj: 9, fo: 3, fa: 8, m: 8, hb: 1},
           ]
