      var maaArchers = [{p: 5, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, b: 1, hb: 2},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 4},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 5},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 1},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 2},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3, hb: 1},
{p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 7, lj: 3, hb: 1},
{p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4},
{p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 1},
{p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 2},
{p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 3},
{p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 4},
{p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 9, lj: 4, fo: 4},
{p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 9, lj: 4, fo: 4, b: 1},
{p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 10, lj: 4, fo: 4, b: 1},
{p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 10, lj: 4, fo: 4, hb: 1, m: 1},
{p: 30, l: true, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 10, lj: 5, fo: 4, m: 2},
{p: 30, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 10, lj: 5, fo: 4, m: 2},
{p: 30, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 4, lj: 7, fo: 6, fa: 2, m: 2, message: 'Sheep done'},
{p: 30, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, lj: 12, fo: 6, fa: 2, m: 2},
{p: 30, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, lj: 12, fo: 4, b: 2, fa: 2, m: 3},
{p: 30, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, lj: 12, fo: 4, b: 2, fa: 2, m: 4},
{p: 30, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, lj: 12, fo: 4, b: 1, hb: 1, fa: 2, m: 5},
{p: 35, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: false, wb: false, lj: 12, fo: 4, b: 1, hb: 1, fa: 2, m: 6},
{p: 40, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, fo: 4, hb: 1, fa: 2, m: 8, message: 'Berries done'},
{p: 45, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, hb: 1, fa: 7, m: 8},
{p: 50, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, hb: 1, fa: 8, m: 8},
{p: 55, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, hb: 1, fa: 9, m: 8},
{p: 60, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, hb: 1, fa: 10, m: 8},
{p: 65, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, hb: 1, fa: 11, m: 8},
{p: 70, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, fa: 13, m: 8},
{p: 70, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, fa: 14, m: 8},
{p: 70, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, fa: 15, m: 8},
{p: 70, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, fa: 16, m: 8},
{p: 70, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: false, lj: 12, fa: 17, m: 8},
{p: 70, l: true, a: 'Feudal', dba: true, hc: false, bs: false, fl: true, wb: true, lj: 12, fa: 18, m: 8},
{p: 70, l: true, a: 'Castle', dba: true, hc: false, bs: false, fl: true, wb: true, lj: 12, fa: 18, m: 8},
]
