      var scoutArchers = [{p: 5, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, b: 1, hb: 2},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 4},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 5},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 1},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 2},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3},
{p: 15, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 6, lj: 3, hb: 1},
{p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3},
{p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3, fo: 1},
{p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3, fo: 2},
{p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3, fo: 3},
{p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3, fo: 4},
{p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3, fo: 4, fa: 1},
{p: 20, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 3, fo: 3, fa: 2, hb: 1},
{p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 4, fo: 4, fa: 2},
{p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 5, fo: 4, fa: 2},
{p: 25, l: false, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 8, lj: 6, fo: 4, fa: 2},
{p: 25, l: true, a: 'Dark', dba: false, hc: false, bs: false, fl: false, wb: false, h: 5, lj: 10, fo: 4, fa: 2},
{p: 25, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 5, lj: 10, fo: 4, fa: 2},
{p: 25, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 4, lj: 10, fo: 4, fa: 2, b: 1},
{p: 25, l: true, a: 'Feudal', dba: false, hc: false, bs: false, fl: false, wb: false, h: 4, lj: 10, fo: 4, fa: 2, hb: 1},
{p: 30, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, h: 3, lj: 10, fo: 4, fa: 3, b: 2},
{p: 30, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, h: 3, lj: 10, fo: 4, fa: 5, hb: 1},
{p: 35, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, h: 3, lj: 10, fo: 4, fa: 6, hb: 1},
{p: 40, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, h: 3, lj: 10, fo: 4, fa: 7, hb: 1, message: 'Sheep done'},
{p: 45, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 10, fo: 4, fa: 11, hb: 1},
{p: 50, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 10, fo: 4, fa: 12, hb: 1},
{p: 55, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 10, fo: 4, fa: 13, hb: 1},
{p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 9, fo: 2, fa: 14, b: 1, m: 3},
{p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 9, fo: 2, fa: 14, b: 1, m: 4},
{p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 9, fo: 2, fa: 14, b: 1, m: 5},
{p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 9, fo: 2, fa: 14, b: 1, m: 6},
{p: 60, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: false, lj: 9, fo: 2, fa: 14, hb: 1, m: 7},
{p: 65, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: true, lj: 9, fo: 2, fa: 14, b: 1, m: 8, message: 'Berries done'},
{p: 65, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: true, lj: 9, fa: 16, b: 1, m: 8},
{p: 65, l: true, a: 'Feudal', dba: true, hc: true, bs: false, fl: false, wb: true, lj: 10, fa: 17, m: 8},
{p: 65, l: true, a: 'Castle', dba: true, hc: true, bs: false, fl: false, wb: true, lj: 10, fa: 18, m: 8},
]
